### ISSUE TITLE
getReport2 returns incorrect numbers for metrics/pageviews.

### ISSUE THREAD

**Issue by cyaris** [pitchmuc/adobe-analytics-api-2.0#95] opened 2023-04-25 22:58 UTC
`getReport2` returns incorrect numbers for `metrics/pageviews`. These do not match the Adobe portal. `getReport` returns numbers that do match the Adobe portal.

**Comment by pitchmuc** [comment] 2023-04-26 07:35
This is not a helpful description.
Can you provide the steps that create the issue.
Anything that you could share is helpful

**Comment by pitchmuc** [comment] 2023-04-26 08:08
Investigating into this, I found the same issue. 
![image](https://user-images.githubusercontent.com/32903178/234510631-aa4292bc-077e-44ea-b489-8d404bb7b103.png)
getReport2 returns: 
![image](https://user-images.githubusercontent.com/32903178/234510710-5ccb1701-ab52-41cd-9f22-9d80d21564bf.png)

Checking the raw response from analytics server, the problem is coming from the Analytics server. 
You would need to open a ticket with Customer Care for this: 
Here is a screenshot of that request: 
![image](https://user-images.githubusercontent.com/32903178/234511497-7b91c578-1ce7-4fa6-90bf-b0f90a8d1d77.png)

It would be best if you reproduce that yourself in your enviornment and send that detail in the ticket.

I'll close it later.

**Comment by cyaris** [comment] 2023-04-26 18:13
Hi @pitchmuc, since this metric returns successfully for `getReport`, I thought it was an issue with `aanalytics2`. Any idea why it works for the `getReport` method but not `getReport2`? I'll gladly submit a customer care ticket but I'm not exactly sure what to say since it's not an issue with the Adobe portal. Thanks!

**Comment by pitchmuc** [comment] 2023-04-27 12:43
Sorry for some reason I miss that it was working for getReport. 
I will check why it is working good for getReport but not getReport2...
In the backend, I am using the same endpoint, so maybe so request modification happen but strange that it is only impacting one metric.

**Comment by pitchmuc** [comment] 2023-04-27 13:10
I found out, it is a bug of a sort. 
It is due to the configuration, I am not keeping the parameter you are using for these options: 
* nonesBehavior
* countRepeatInstances

I override them by the default configuration. 
But if you are doing that: 
```python
data1 = ags.getReport('pageview_request.json')
data2 = ags.getReport2('pageview_request.json',countRepeatInstances=True,returnsNone=True)
```
It should provide you the same result. 

I willl fix it and keep the one set in your JSON and not override them, except if you want to. 
Sorry for that, fix is going live today.

**Closed** 2023-04-28 07:35 UTC
Labels: bug
